use regex::Regex;
use std::collections::{HashMap, HashSet};
use std::fmt;

use crate::libs;
use crate::parsers;
use crate::parsers::parser_line::tokens_to_redirections;
use crate::shell;
use crate::tools;

#[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, Hash)]
pub struct WaitStatus(i32, i32, i32);

impl WaitStatus {
    pub fn from_exited(pid: i32, status: i32) -> Self {
        WaitStatus(pid, 0, status)
    }

    pub fn from_signaled(pid: i32, sig: i32) -> Self {
        WaitStatus(pid, 1, sig)
    }

    pub fn from_stopped(pid: i32, sig: i32) -> Self {
        WaitStatus(pid, 2, sig)
    }

    pub fn from_continuted(pid: i32) -> Self {
        WaitStatus(pid, 3, 0)
    }

    pub fn from_others() -> Self {
        WaitStatus(0, 9, 9)
    }

    pub fn from_error(errno: i32) -> Self {
        WaitStatus(0, 255, errno)
    }

    pub fn empty() -> Self {
        WaitStatus(0, 0, 0)
    }

    pub fn is_error(&self) -> bool {
        self.1 == 255
    }

    pub fn is_others(&self) -> bool {
        self.1 == 9
    }

    pub fn is_signaled(&self) -> bool {
        self.1 == 1
    }

    pub fn get_errno(&self) -> nix::Error {
        nix::Error::from_raw(self.2)
    }

    pub fn is_exited(&self) -> bool {
        self.0 != 0 && self.1 == 0
    }

    pub fn is_stopped(&self) -> bool {
        self.1 == 2
    }

    pub fn is_continued(&self) -> bool {
        self.1 == 3
    }

    pub fn get_pid(&self) -> i32 {
        self.0
    }

    fn _get_signaled_status(&self) -> i32 {
        self.2 + 128
    }

    pub fn get_signal(&self) -> i32 {
        self.2
    }

    pub fn get_name(&self) -> String {
        if self.is_exited() {
            "Exited".to_string()
        } else if self.is_stopped() {
            "Stopped".to_string()
        } else if self.is_continued() {
            "Continued".to_string()
        } else if self.is_signaled() {
            "Signaled".to_string()
        } else if self.is_others() {
            "Others".to_string()
        } else if self.is_error() {
            "Error".to_string()
        } else {
            format!("unknown: {}", self.2)
        }
    }

    pub fn get_status(&self) -> i32 {
        if self.is_exited() {
            self.2
        } else {
            self._get_signaled_status()
        }
    }
}

impl fmt::Debug for WaitStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let mut formatter = f.debug_struct("WaitStatus");
        formatter.field("pid", &self.0);
        let name = self.get_name();
        formatter.field("name", &name);
        formatter.field("ext", &self.2);
        formatter.finish()
    }
}

pub type Token = (String, String);
pub type Tokens = Vec<Token>;
pub type Redirection = (String, String, String);

#[derive(Debug)]
pub struct LineInfo {
    // e.g. echo 'foo
    // is not a completed line, need to turn to multiple-line mode.
    pub tokens: Tokens,
    pub is_complete: bool,
}

impl LineInfo {
    pub fn new(tokens: Tokens) -> Self {
        LineInfo {
            tokens,
            is_complete: true,
        }
    }
}

/// A heredoc body waiting in `Shell::heredocs` for its command to be built.
#[derive(Debug, Clone)]
pub struct Heredoc {
    pub body: String,
    /// The delimiter was quoted, so the body is literal.
    pub quoted: bool,
    /// A copy made for a single run (see `heredoc::apply_to_bodies`), dropped
    /// as soon as that run picks it up.
    pub transient: bool,
}

/// Prefix for marker tokens generated by the heredoc preprocessor. The real
/// heredoc body is stored in `Shell::heredocs` until the command is built.
pub const HEREDOC_MARKER_PREFIX: &str = "__cicada_heredoc_";

///
/// command line: `ls 'foo bar' 2>&1 > /dev/null < one-file` would be:
/// Command {
///     tokens: [("", "ls"), ("", "-G"), ("\'", "foo bar")],
///     redirects_to: [
///         ("2", ">", "&1"),
///         ("1", ">", "/dev/null"),
///     ],
///     redirect_from: Some(("<", "one-file")),
/// }
///
#[derive(Debug)]
pub struct Command {
    pub tokens: Tokens,
    pub redirects_to: Vec<Redirection>,
    pub redirect_from: Option<Token>,
    /// Body of the heredoc feeding this command's stdin, already expanded.
    pub heredoc: Option<String>,
}

#[derive(Debug)]
pub struct CommandLine {
    pub line: String,
    pub commands: Vec<Command>,
    pub envs: HashMap<String, String>,
    pub background: bool,
}

/// Is this token the operator `op` as written in the source?
///
/// A token only acts as an operator when it carries no quote marker: `cat '<'
/// f` passes `<` to `cat`, and a `<` that arrived from an expansion is data
/// too, because expansion marks such words (see `shell::SEP_GENERATED`).
fn is_op(token: &Token, op: &str) -> bool {
    token.0.is_empty() && token.1 == op
}

fn is_redirect_from_op(token: &Token) -> bool {
    is_op(token, "<") || is_op(token, "<<<")
}

/// Is this here-string operand a heredoc marker the preprocessor wrote?
///
/// Two things have to hold, and both are out of reach of a word that arrived
/// from an expansion: the name carries the session id (see
/// `heredoc::next_marker`), and the word is single quoted, which only the
/// source text can be -- an expanded value never brings a quote marker with
/// it. Without this, `cat <<< "$untrusted"` could be steered into reading the
/// body of some other heredoc in the same run.
fn is_heredoc_marker(sep: &str, value: &str) -> bool {
    sep == "'" && value.starts_with(HEREDOC_MARKER_PREFIX)
}

impl Command {
    pub fn from_tokens(tokens: Tokens, sh: &mut shell::Shell) -> Result<Command, String> {
        let mut tokens_new = tokens.clone();
        let mut redirects_from_type = String::new();
        let mut redirects_from_value = String::new();
        let mut heredoc = None;
        let mut has_redirect_from = tokens_new.iter().any(is_redirect_from_op);

        let mut len = tokens_new.len();
        while has_redirect_from {
            if let Some(idx) = tokens_new.iter().position(|x| is_op(x, "<")) {
                redirects_from_type = "<".to_string();
                tokens_new.remove(idx);
                len -= 1;
                if len > idx {
                    redirects_from_value = tokens_new.remove(idx).1;
                    len -= 1;
                }
            }
            if let Some(idx) = tokens_new.iter().position(|x| is_op(x, "<<<")) {
                redirects_from_type = "<<<".to_string();
                tokens_new.remove(idx);
                len -= 1;
                let mut value_sep = String::new();
                if len > idx {
                    let token = tokens_new.remove(idx);
                    value_sep = token.0;
                    redirects_from_value = token.1;
                    len -= 1;
                }
                if is_heredoc_marker(&value_sep, &redirects_from_value) {
                    // a here-string the heredoc preprocessor wrote: the body it
                    // stands for becomes this command's stdin. A word that only
                    // looks like a marker stays the here-string it is.
                    if let Some(body) =
                        crate::parsers::heredoc::take_body(sh, &redirects_from_value)
                    {
                        heredoc = Some(body);
                        redirects_from_type = String::new();
                        redirects_from_value = String::new();
                    }
                }
            }

            has_redirect_from = tokens_new.iter().any(is_redirect_from_op);
        }

        let tokens_final;
        let redirects_to;
        match tokens_to_redirections(&tokens_new) {
            Ok((_tokens, _redirects_to)) => {
                tokens_final = _tokens;
                redirects_to = _redirects_to;
            }
            Err(e) => {
                return Err(e);
            }
        }

        let redirect_from = if redirects_from_type.is_empty() {
            None
        } else {
            Some((redirects_from_type, redirects_from_value))
        };

        Ok(Command {
            tokens: tokens_final,
            redirects_to,
            redirect_from,
            heredoc,
        })
    }

    pub fn has_redirect_from(&self) -> bool {
        self.redirect_from.is_some() && self.redirect_from.clone().unwrap().0 == "<"
    }

    pub fn has_here_string(&self) -> bool {
        self.redirect_from.is_some() && self.redirect_from.clone().unwrap().0 == "<<<"
    }

    pub fn is_builtin(&self) -> bool {
        // a command can be all redirection and no word, as in `> foo` or a
        // heredoc with nothing in front of it -- there is no name to match
        !self.tokens.is_empty() && tools::is_builtin(&self.tokens[0].1)
    }
}

#[derive(Debug, Clone, Default)]
pub struct Job {
    pub cmd: String,
    pub id: i32,
    pub gid: i32,
    pub pids: Vec<i32>,
    pub pids_stopped: HashSet<i32>,
    pub status: String,
    pub is_bg: bool,
}

impl Job {
    pub fn all_members_stopped(&self) -> bool {
        for pid in &self.pids {
            if !self.pids_stopped.contains(pid) {
                return false;
            }
        }
        true
    }

    pub fn all_members_running(&self) -> bool {
        self.pids_stopped.is_empty()
    }
}

#[allow(dead_code)]
#[derive(Clone, Debug, Default)]
pub struct CommandResult {
    pub gid: i32,
    pub status: i32,
    pub stdout: String,
    pub stderr: String,
}

impl CommandResult {
    pub fn new() -> CommandResult {
        CommandResult {
            gid: 0,
            status: 0,
            stdout: String::new(),
            stderr: String::new(),
        }
    }

    pub fn from_status(gid: i32, status: i32) -> CommandResult {
        CommandResult {
            gid,
            status,
            stdout: String::new(),
            stderr: String::new(),
        }
    }

    pub fn error() -> CommandResult {
        CommandResult {
            gid: 0,
            status: 1,
            stdout: String::new(),
            stderr: String::new(),
        }
    }
}

#[allow(dead_code)]
#[derive(Clone, Debug, Default)]
pub struct CommandOptions {
    pub background: bool,
    pub isatty: bool,
    pub capture_output: bool,
    pub envs: HashMap<String, String>,
}

fn split_tokens_by_pipes(tokens: &[Token]) -> Vec<Tokens> {
    let mut cmd = Vec::new();
    let mut cmds = Vec::new();
    for token in tokens {
        let sep = &token.0;
        let value = &token.1;
        if sep.is_empty() && value == "|" {
            if cmd.is_empty() {
                return Vec::new();
            }
            cmds.push(cmd.clone());
            cmd = Vec::new();
        } else {
            cmd.push(token.clone());
        }
    }
    if cmd.is_empty() {
        return Vec::new();
    }
    cmds.push(cmd.clone());
    cmds
}

pub(crate) fn drain_env_tokens(tokens: &mut Tokens) -> HashMap<String, String> {
    let mut envs: HashMap<String, String> = HashMap::new();
    let mut n = 0;
    // `(?s)` so that a value spanning a newline -- `A="one\ntwo"` -- is still
    // recognized as an assignment instead of being run as a command.
    let ptn_env = r"(?s)^([a-zA-Z0-9_]+)=(.*)$";
    let re = Regex::new(ptn_env).unwrap();
    for (sep, text) in tokens.iter() {
        // A word expansion marked as data (`shell::SEP_GENERATED`) is still an
        // assignment if that is how it was written: `B='x>y'; A=$B cmd` sets
        // `A` for `cmd`, it does not redirect.
        let sep_blocks = !sep.is_empty() && sep != shell::SEP_GENERATED;
        if sep_blocks || !libs::re::re_contains(text, ptn_env) {
            break;
        }

        for cap in re.captures_iter(text) {
            let name = cap[1].to_string();
            envs.insert(name, cap[2].to_string());
        }

        n += 1;
    }
    if n > 0 {
        tokens.drain(0..n);
    }
    envs
}

impl CommandLine {
    pub fn from_line(line: &str, sh: &mut shell::Shell) -> Result<CommandLine, String> {
        let linfo = parsers::parser_line::parse_line(line);
        let mut tokens = linfo.tokens;
        shell::do_expansion(sh, &mut tokens);
        let envs = drain_env_tokens(&mut tokens);

        let mut background = false;
        let len = tokens.len();
        if len > 1 && is_op(&tokens[len - 1], "&") {
            background = true;
            tokens.pop();
        }

        let mut commands = Vec::new();
        for sub_tokens in split_tokens_by_pipes(&tokens) {
            match Command::from_tokens(sub_tokens, sh) {
                Ok(c) => {
                    commands.push(c);
                }
                Err(e) => {
                    return Err(e);
                }
            }
        }

        Ok(CommandLine {
            line: line.to_string(),
            commands,
            envs,
            background,
        })
    }

    pub fn is_empty(&self) -> bool {
        self.commands.is_empty()
    }

    pub fn with_pipeline(&self) -> bool {
        self.commands.len() > 1
    }

    pub fn is_single_and_builtin(&self) -> bool {
        self.commands.len() == 1 && self.commands[0].is_builtin()
    }
}

#[cfg(test)]
mod tests {
    use super::is_heredoc_marker;
    use super::HEREDOC_MARKER_PREFIX;

    #[test]
    fn test_only_the_preprocessors_own_marker_is_honored() {
        let marker = format!("{}9f2c4b_0", HEREDOC_MARKER_PREFIX);

        // as the preprocessor writes it
        assert!(is_heredoc_marker("'", &marker));

        // a value that arrived from an expansion never carries a quote
        // marker, so `cat <<< "$untrusted"` cannot reach a heredoc body
        assert!(!is_heredoc_marker("", &marker));
        assert!(!is_heredoc_marker("\"", &marker));
        assert!(!is_heredoc_marker("`", &marker));

        // an ordinary here-string stays one
        assert!(!is_heredoc_marker("'", "some text"));
    }
}
